name: Serving CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kodingan
    - uses: actions/checkout@v3

    # 2. Siapin Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    # 3. Install Library (Biar gak error pas import)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pandas scikit-learn mlflow numpy requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 4. Cek Error Kodingan (Linting)
    # Kita disable Warning (R,C) biar tetep centang hijau walau kodingan berantakan dikit
    - name: Lint with pylint
      run: |
        pylint --disable=R,C *.py